// src/App.tsx
import { useState, useMemo } from 'react';
import { Header } from './components/Header';
import { Sidebar } from './components/Sidebar';
import { FilterPanel } from './components/FilterPanel';
import { FavoritesRow } from './components/FavoritesRow';
import { RecentlyAccessedRow } from './components/RecentlyAccessedRow';
import { AppGrid } from './components/AppGrid';
import { StyleGuide } from './components/StyleGuide';
import { applications as initialApps } from './data/applications';
import { Application, RoleFilter, SortFilter } from './types';

export default function App() {
  const [currentView, setCurrentView] = useState('home');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedRole, setSelectedRole] = useState<RoleFilter>('All');
  const [selectedSort, setSelectedSort] = useState<SortFilter>('all');
  const [apps, setApps] = useState<Application[]>(initialApps);

  const handleToggleFavorite = (id: string) => {
    setApps((prevApps) =>
      prevApps.map((app) =>
        app.id === id ? { ...app, isFavorite: !app.isFavorite } : app
      )
    );
  };

  const filteredApps = useMemo(() => {
    let filtered = apps;

    // Filter by search query
    if (searchQuery) {
      filtered = filtered.filter(
        (app) =>
          app.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
          app.category.toLowerCase().includes(searchQuery.toLowerCase())
      );
    }

    // Filter by role
    if (selectedRole !== 'All') {
      filtered = filtered.filter((app) => app.roles.includes(selectedRole));
    }

    // Filter by sort option
    switch (selectedSort) {
      case 'recent':
        filtered = filtered.filter((app) => app.lastAccessed);
        filtered.sort((a, b) => {
          if (!a.lastAccessed || !b.lastAccessed) return 0;
          return b.lastAccessed.getTime() - a.lastAccessed.getTime();
        });
        break;
      case 'favorites':
        filtered = filtered.filter((app) => app.isFavorite);
        break;
      case 'most-used':
        filtered = filtered.filter((app) => app.lastAccessed);
        break;
    }

    return filtered;
  }, [apps, searchQuery, selectedRole, selectedSort]);

  const showFavoritesRow = currentView === 'home' && selectedSort === 'all' && !searchQuery;
  const showRecentRow = currentView === 'home' && selectedSort === 'all' && !searchQuery;

  return (
    <div className="min-h-screen bg-[#141414]">
      {/* Header */}
      <Header searchQuery={searchQuery} onSearchChange={setSearchQuery} />

      {/* Sidebar */}
      <Sidebar currentView={currentView} onViewChange={setCurrentView} />

      {/* Main Content - Fixed padding to prevent overlap */}
      <main className="ml-[72px] pt-[68px]">
        <div className="px-8 py-8 max-w-[2000px]">
          {currentView === 'style-guide' ? (
            <StyleGuide />
          ) : currentView === 'favorites' ? (
            <div className="space-y-8">
              <div>
                <h1 className="text-3xl font-bold text-white mb-2">
                  Favorite Applications
                </h1>
                <p className="text-base text-gray-400">Quick access to your most used applications</p>
              </div>
              <AppGrid
                apps={apps.filter((app) => app.isFavorite)}
                title="All Favorites"
                onToggleFavorite={handleToggleFavorite}
              />
            </div>
          ) : (
            <div className="space-y-8">
              {/* Filter Panel */}
              <FilterPanel
                selectedRole={selectedRole}
                onRoleChange={setSelectedRole}
                selectedSort={selectedSort}
                onSortChange={setSelectedSort}
              />

              {/* Favorites Row */}
              {showFavoritesRow && (
                <FavoritesRow apps={apps} onToggleFavorite={handleToggleFavorite} />
              )}

              {/* Recently Accessed Row */}
              {showRecentRow && (
                <RecentlyAccessedRow apps={apps} onToggleFavorite={handleToggleFavorite} />
              )}

              {/* All Applications Grid */}
              <AppGrid
                apps={filteredApps}
                title={
                  selectedSort === 'all'
                    ? 'All Applications'
                    : selectedSort === 'recent'
                    ? 'Recently Accessed'
                    : selectedSort === 'favorites'
                    ? 'Favorite Applications'
                    : 'Most Used Applications'
                }
                onToggleFavorite={handleToggleFavorite}
              />
            </div>
          )}
        </div>
      </main>
    </div>
  );
}

// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'payments-dashboard';
}

<div class="min-h-screen bg-[#141414]">
  <!-- Voice Message Notification -->
  <div
    *ngIf="voiceMessage"
    class="fixed top-[80px] left-1/2 transform -translate-x-1/2 z-50 px-6 py-3 rounded-lg backdrop-blur-md border"
    [ngClass]="{
      'bg-green-500/20 border-green-500/50 text-green-300': voiceMessage.includes('Opening'),
      'bg-red-500/20 border-red-500/50 text-red-300': voiceMessage.includes('couldn\'t')
    }"
  >
    {{ voiceMessage }}
  </div>

  <!-- Header -->
  <app-header
    [searchQuery]="searchQuery"
    (searchChange)="onSearchChange($event)"
  ></app-header>

  <!-- Sidebar -->
  <app-sidebar
    [currentView]="currentView"
    (viewChange)="onViewChange($event)"
    (voiceToggle)="onVoiceToggle($event)"
  ></app-sidebar>

  <!-- Main Content -->
  <main class="ml-[72px] pt-[68px]">
    <div class="px-8 py-8 max-w-[2000px]">
      <!-- Favorites View -->
      <ng-container *ngIf="currentView === 'favorites'">
        <div class="space-y-8">
          <div>
            <h1 class="text-3xl font-bold text-white mb-2">
              Favorite Applications
            </h1>
            <p class="text-base text-gray-400">
              Quick access to your most used applications
            </p>
          </div>
          <app-grid
            [applications]="favoriteApps"
            title="All Favorites"
            (toggleFavorite)="onToggleFavorite($event)"
            (launchApp)="onLaunchApp($event)"
          ></app-grid>
        </div>
      </ng-container>

      <!-- Home View -->
      <ng-container *ngIf="currentView === 'home'">
        <div class="space-y-8">
          <!-- Filter Panel -->
          <app-filter-panel
            [selectedRole]="selectedRole"
            [selectedSort]="selectedSort"
            (roleChange)="onRoleChange($event)"
            (sortChange)="onSortChange($event)"
          ></app-filter-panel>

          <!-- Favorites Row -->
          <app-favorites-row
            *ngIf="showFavoritesRow && favoriteApps.length > 0"
            [applications]="favoriteApps"
            (toggleFavorite)="onToggleFavorite($event)"
            (launchApp)="onLaunchApp($event)"
          ></app-favorites-row>

          <!-- Recently Accessed Row -->
          <app-recently-accessed-row
            *ngIf="showRecentRow && recentApps.length > 0"
            [applications]="recentApps"
            (toggleFavorite)="onToggleFavorite($event)"
            (launchApp)="onLaunchApp($event)"
          ></app-recently-accessed-row>

          <!-- All Applications Grid -->
          <app-grid
            [applications]="filteredApps"
            [title]="
              selectedSort === 'all'
                ? 'All Applications'
                : selectedSort === 'recent'
                ? 'Recently Accessed'
                : selectedSort === 'favorites'
                ? 'Favorite Applications'
                : 'Most Used Applications'
            "
            (toggleFavorite)="onToggleFavorite($event)"
            (launchApp)="onLaunchApp($event)"
          ></app-grid>
        </div>
      </ng-container>
    </div>
  </main>
</div>
